# Site settings
title: RayHightower.com
description: Thoughts about Ruby, Rails, iOS, the Internet of Things (IoT), software development, and business growth.
tagline: Ruby, Rails, & IoT
baseurl: / # the subpath of your site, e.g. /blog/
url: "http://rayhightower.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title/
excerpt_link: "Continue reading &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Disqus Comments
disqus_short_name: rayhightower
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-330946-28

# Twitter
twitter_username: rayhightower
twitter_user:
twitter_tweet_button: true
  
gems:
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml
author:
  name:           'Raymond T. Hightower'
  url:            https://twitter.com/rayhightower

paginate:         5

github_username: rayhightower
github:
  repo:           https://github.com/rayhightower

