# Site settings
title: RayHightower.com
description: Thoughts about Ruby, Rails, iOS, the Internet of Things (IoT), software development, and business growth.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rayhightower.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title/

twitter_username: rayhightower
github_username:  


# Build settings
markdown: redcarpet
# markdown: rdiscount
# rdiscount:
redcarpet:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb
  

# Disqus Comments
disqus_short_name: rayhightower
# disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-330946-28
# google_analytics_tracking_id:

# Twitter
twitter_user:
twitter_tweet_button: true
  

