# Site settings
title: RayHightower.com
description: Tech company founder. Commercial real estate investor.
tagline: Tech company founder. Commercial real estate investor.
baseurl: / # the subpath of your site, e.g. /blog/
url: "http://rayhightower.com" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title/
excerpt_link: "Continue reading &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: <!--more-->
future: true # Let future blog posts be published

# Build settings
markdown: kramdown

# Disqus Comments
disqus_short_name: rayhightower
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-330946-28

# Twitter
twitter_username: rayhightower
twitter_user:
twitter_tweet_button: true

plugins:
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml
author:
  name: 'Raymond T. Hightower'
  url: https://twitter.com/rayhightower

paginate: 5
paginate_path: "/page:num/"

github_username: rayhightower
github:
  repo: https://github.com/rayhightower

